name: revgeocoder
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs==23.1.0
  - backports==1.0
  - backports.functools_lru_cache==1.6.5
  - blosc==1.21.5
  - boto3==1.28.75
  - botocore==1.31.75
  - branca==0.6.0
  - brotli==1.1.0
  - brotli-bin==1.1.0
  - brotli-python==1.1.0
  - bzip2==1.0.8
  - c-ares==1.20.1
  - ca-certificates==2023.7.22
  - cairo==1.18.0
  - certifi==2023.7.22
  - cfitsio==4.3.0
  - charset-normalizer==3.3.0
  - click==8.1.7
  - click-plugins==1.1.1
  - cligj==0.7.2
  - contourpy==1.1.1
  - cycler==0.12.1
  - exceptiongroup==1.1.3
  - expat==2.5.0
  - fiona==1.9.5
  - folium==0.14.0
  - font-ttf-dejavu-sans-mono==2.37
  - font-ttf-inconsolata==3.000
  - font-ttf-source-code-pro==2.038
  - font-ttf-ubuntu==0.83
  - fontconfig==2.14.2
  - fonts-conda-ecosystem==1
  - fonts-conda-forge==1
  - fonttools==4.43.1
  - freetype==2.12.1
  - freexl==2.0.0
  - gdal==3.7.2
  - geographiclib==1.52
  - geopandas==0.14.0
  - geopandas-base==0.14.0
  - geopy==2.4.0
  - geos==3.12.0
  - geotiff==1.7.1
  - gettext==0.21.1
  - giflib==5.2.1
  - greenlet==3.0.0
  - h11==0.14.0
  - hdf4==4.2.15
  - hdf5==1.14.2
  - icu==73.2
  - idna==3.4
  - importlib-metadata==6.8.0
  - jinja2==3.1.2
  - jmespath==1.0.1
  - joblib==1.3.2
  - json-c==0.17
  - kealib==1.5.2
  - kiwisolver==1.4.5
  - krb5==1.21.2
  - lcms2==2.15
  - lerc==4.0.0
  - libaec==1.1.2
  - libarchive==3.7.2
  - libblas==3.9.0
  - libboost-headers==1.82.0
  - libbrotlicommon==1.1.0
  - libbrotlidec==1.1.0
  - libbrotlienc==1.1.0
  - libcblas==3.9.0
  - libcurl==8.4.0
  - libcxx==16.0.6
  - libdeflate==1.19
  - libedit==3.1.20191231
  - libev==4.33
  - libexpat==2.5.0
  - libffi==3.4.2
  - libgdal==3.7.2
  - libgfortran
  - libgfortran5
  - libglib==2.78.0
  - libiconv==1.17
  - libjpeg-turbo==3.0.0
  - libkml==1.3.0
  - liblapack==3.9.0
  - libnetcdf==4.9.2
  - libnghttp2==1.52.0
  - libopenblas==0.3.24
  - libpng==1.6.39
  - libpq==16.0
  - librttopo==1.1.0
  - libspatialindex==1.9.3
  - libspatialite==5.1.0
  - libsqlite==3.43.2
  - libssh2==1.11.0
  - libtiff==4.6.0
  - libwebp-base==1.3.2
  - libxcb==1.15
  - libxml2==2.11.5
  - libzip==1.10.1
  - libzlib==1.2.13
  - llvm-openmp==17.0.3
  - lz4-c==1.9.4
  - lzo==2.10
  - mapclassify==2.6.1
  - markupsafe==2.1.3
  - matplotlib-base==3.8.0
  - minizip==4.0.1
  - munch==4.0.0
  - munkres==1.1.4
  - ncurses==6.4
  - networkx==3.2
  - nspr==4.35
  - nss==3.94
  - numpy==1.26.0
  - openjpeg==2.5.0
  - openssl==3.1.4
  - outcome==1.3.0.post0
  - packaging==23.2
  - pandas==2.1.1
  - pcre2==10.40
  - pillow==10.1.0
  - pip==23.3
  - pixman==0.42.2
  - poppler==23.10.0
  - poppler-data==0.4.12
  - postgresql==16.0
  - prettytable==3.9.0
  - proj==9.3.0
  - psycopg2==2.9.7
  - pthread-stubs==0.4
  - pyparsing==3.1.1
  - pyproj==3.6.1
  - pysocks==1.7.1
  - python==3.12.0
  - python-dateutil==2.8.2
  - python-dotenv==1.0.0
  - python-tzdata==2023.3
  - python_abi==3.12
  - pytz==2023.3.post1
  - readline==8.2
  - requests==2.31.0
  - rtree==1.1.0
  - s3transfer==0.7.0
  - scikit-learn==1.3.1
  - scipy==1.11.3
  - selenium==4.15.1
  - selenium-manager==4.15.0
  - setuptools==68.2.2
  - shapely==2.0.2
  - six==1.16.0
  - snappy==1.1.10
  - sniffio==1.3.0
  - sortedcontainers==2.4.0
  - sqlalchemy==2.0.22
  - sqlite==3.43.2
  - threadpoolctl==3.2.0
  - tiledb==2.16.3
  - tk==8.6.13
  - trio==0.23.1
  - trio-websocket==0.11.1
  - typing-extensions==4.8.0
  - typing_extensions==4.8.0
  - tzcode==2023c
  - tzdata==2023c
  - uriparser==0.9.7
  - urllib3==1.26.18
  - wcwidth==0.2.9
  - wheel==0.41.2
  - wsproto==1.2.0
  - xerces-c==3.2.4
  - xorg-libxau==1.0.11
  - xorg-libxdmcp==1.1.3
  - xyzservices==2023.10.0
  - xz==5.2.6
  - zipp==3.17.0
  - zlib==1.2.13
  - zstd==1.5.5
